#!/usr/bin/env bash
# Displays listening ports: Show only listening ports
# netstat <--- symbolically displays the contents of various network-related data
# l <--- listening
# p <--- program (PID and name of the program)

netstat -lp